platform: linux
image_resource:
    type: docker-image
    source:
        repository: nexus:8083/alpine
        tag: 3.10
        insecure_registries: [ "nexus:8083" ]

inputs:
  - name: src               # Mandatory.
  - name: recipient         # Mandatory.
    path: inputs/recipient  # Optional. Default to "name". Relative to Current Working Directory.
    optional: true          # Optional. Default to "false"

outputs:
  - name: message           # Mandatory.
    path: outputs/message   # Optional. Default to "name". Relative to CWD.

run:
    path: src/scripts/greet.sh
