resources:
  - name: src
    type: git
    icon: git
    source:
        uri: http://gogs:3000/mktd10-concourse/my-react-app.git
        branch: master
  - name: ci
    type: git
    icon: git
    source:
        uri: http://gogs:3000/mktd10-concourse/04a-shared-nodemodules.git
        branch: master

jobs:
  - name: deliver-app
    plan:
      - get: src
      - get: ci
      - task: init
        file: ci/tasks/npm-install.yml
      - task: build
        file: ci/tasks/npm-build.yml
      - task: test
        file: ci/tasks/npm-test.yml
